name: "Nitro Schema Validate"
description: "Validates GraphQL schemas against the Nitro registry"
author: "ChilliCream"
branding:
  icon: "check-circle"
  color: "purple"

inputs:
  stage:
    description: "The name of the stage"
    required: true
  api-id:
    description: "The ID of the API"
    required: true
  schema-file:
    description: "The path to the graphql file with the schema definition"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
    secret: true
  cloud-url:
    description: "The URL of the Nitro registry"
    required: false
  job-id:
    description: "The ID of the current job"
    required: false
    default: ${{ job.check_run_id }}
  commentMode:
    description: "Controls pull request feedback on validation failure: comment, review, or none"
    required: false
    default: "none"

runs:
  using: "node20"
  main: "dist/index.js"
