name: 🔄 Update Nitro CLI Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to update to
        required: true
        type: string

run-name: "🔄 Update to ${{ inputs.version }}"

permissions:
  contents: write

jobs:
  update:
    uses: ChilliCream/nitro-github-actions/.github/workflows/update-cli-version.yaml@637a996105bb4c2b27adb0e5e0818ecfd8aab402
    with:
      version: ${{ inputs.version }}
